import { useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import AuthLayout from "./AuthLayout";
import { adminLogin, adminRegister, adminVerify } from "../../Services/admin.api";

export default function AdminAuthPage({ mode }) {
  const navigate = useNavigate(); const location = useLocation();
  const [form, setForm] = useState({ name: "", email: location.state?.email || "", password: "", registrationCode: "", otp: "" }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const set = key => event => setForm(previous => ({ ...previous, [key]: event.target.value }));
  async function submit(event) { event.preventDefault(); setError(""); setLoading(true); try { if (mode === "login") { await adminLogin({ email: form.email.trim(), password: form.password }); navigate("/admin", { replace: true }); } else if (mode === "register") { await adminRegister({ name: form.name.trim(), email: form.email.trim(), password: form.password, registrationCode: form.registrationCode.trim() }); navigate("/admin/verify", { state: { email: form.email.trim() }, replace: true }); } else { await adminVerify({ email: form.email.trim(), otp: form.otp }); navigate("/admin/login", { replace: true }); } } catch (e) { setError(e?.response?.data?.message || "Unable to complete this request."); } finally { setLoading(false); } }
  const verify = mode === "verify"; const register = mode === "register"; const title = verify ? "Verify your email" : register ? "Create admin account" : "Admin sign in";
  return <AuthLayout><section className="relative z-20 mx-auto w-full max-w-md px-5 py-20"><form onSubmit={submit} className="rounded-[28px] border border-white/10 bg-[#0a0f0b]/95 p-7 shadow-2xl backdrop-blur-xl sm:p-9"><p className="text-[10px] font-semibold uppercase tracking-[.25em] text-[#4ade80]">BYTECODEE ADMIN</p><h1 className="mt-4 text-3xl font-semibold text-white">{title}</h1><p className="mt-2 text-sm leading-6 text-[#9aa59e]">{verify ? "Enter the six-digit code we sent to your email." : register ? "Access is limited to authorized BYTECODEE administrators." : "Use your secure administrator credentials."}</p>{register && <Field label="Full name" value={form.name} onChange={set("name")} autoComplete="name" />}{!verify && <Field label="Email address" type="email" value={form.email} onChange={set("email")} autoComplete="email" />}{verify && <Field label="Email address" type="email" value={form.email} onChange={set("email")} autoComplete="email" />}{!verify && <Field label="Password" type="password" value={form.password} onChange={set("password")} autoComplete={register ? "new-password" : "current-password"} />}{register && <Field label="Admin registration secret" type="password" value={form.registrationCode} onChange={set("registrationCode")} />}{verify && <Field label="6-digit verification code" inputMode="numeric" maxLength="6" value={form.otp} onChange={set("otp")} />}{error && <p className="mt-4 rounded-xl bg-red-500/10 p-3 text-sm text-red-300">{error}</p>}<button disabled={loading} className="mt-6 w-full rounded-xl bg-[#4ade80] px-4 py-3 text-sm font-semibold text-black transition hover:bg-[#86efac] disabled:opacity-50">{loading ? "Please wait…" : verify ? "Verify account" : register ? "Create account" : "Sign in"}</button><p className="mt-6 text-center text-sm text-[#9aa59e]">{register ? <>Already verified? <Link className="text-[#4ade80]" to="/admin/login">Sign in</Link></> : <>Need an admin account? <Link className="text-[#4ade80]" to="/admin/register">Register</Link></>}</p></form></section></AuthLayout>;
}
function Field({ label, ...props }) { return <label className="mt-5 block text-sm text-[#d9e0da]"><span>{label}</span><input required {...props} className="mt-2 w-full rounded-xl border border-white/10 bg-black/25 px-4 py-3 text-white outline-none placeholder:text-white/25 focus:border-[#4ade80]" /></label>; }
